CREATE TABLE COMPRADORES (
ID NUMBER PRIMARY KEY,
NOME VARCHAR2(30) NOT NULL,
ENDERECO VARCHAR2(30) NOT NULL,
TELEFONE VARCHAR2(20) NOT NULL
);

CREATE SEQUENCE ID_COMPRADORES_SEQ;

INSERT INTO COMPRADORES (ID, NOME, ENDERECO, TELEFONE)
VALUES (ID_COMPRADORES_SEQ.NEXTVAL, 'FLAVIO', 'RUA DO OUVIDOR 123', '(11) 1111-1111');

INSERT INTO COMPRADORES (ID, NOME, ENDERECO, TELEFONE)
VALUES (ID_COMPRADORES_SEQ.NEXTVAL, 'NICO', 'AV. PRESIDENTE VARGAS 123', '(11) 2222-2222');

SELECT * FROM COMPRADORES;

SET LINESIZE 100;

SELECT * FROM COMPRADORES;

ALTER TABLE COMPRAS
ADD (COMPRADOR_ID NUMBER);

UPDATE COMPRAS
SET COMPRADOR_ID = 1 WHERE ID <= 20;

UPDATE COMPRAS
SET COMPRADOR_ID = 2 WHERE ID > 20;

SET LINESIZE 150;

SELECT * FROM COMPRAS;

SELECT * FROM COMPRAS, COMPRADORES;
SELECT OBSERVACOES, VALOR, NOME FROM COMPRAS, COMPRADORES;

SELECT OBSERVACOES, VALOR, NOME FROM COMPRAS 
JOIN COMPRADORES ON COMPRAS.COMPRADOR_ID = COMPRADORES.ID;

ALTER TABLE COMPRAS
ADD FOREIGN KEY (COMPRADOR_ID) REFERENCES COMPRADORES(ID);

INSERT INTO COMPRAS(ID, VALOR, DATA, OBSERVACOES, FORMA_PAGTO, COMPRADOR_ID)
VALUES (ID_SEQ.NEXTVAL, 500, '10-JAN-2010', 'COMPRAS DE JANEIRO', 'CARTAO', 100);

INSERT INTO COMPRAS(ID, VALOR, DATA, OBSERVACOES, FORMA_PAGTO, COMPRADOR_ID)
VALUES (ID_SEQ.NEXTVAL, 500, '10-JAN-2010', 'COMPRAS DE JANEIRO', 'CARTAO', 1);

SELECT * FROM COMPRAS;

SELECT NOME, VALOR FROM COMPRAS JOIN COMPRADORES
ON COMPRAS.COMPRADOR_ID = COMPRADORES.ID
WHERE DATA < '09-07-2010';

SELECT * FROM COMPRAS JOIN COMPRADORES 
ON COMPRAS.COMPRADOR_ID = COMPRADORES.ID
WHERE COMPRADOR_ID = 1;

SELECT COMPRAS.* FROM COMPRAS JOIN COMPRADORES
ON COMPRAS.COMPRADOR_ID = COMPRADORES.ID
WHERE NOME LIKE 'FLAVIO%';

SELECT NOME, SUM(VALOR) AS SOMA FROM COMPRAS JOIN COMPRADORES
ON COMPRAS.COMPRADOR_ID - COMPRADORES.ID
GROUP BY NOME;