SELECT SUM(VALOR) FROM COMPRAS;

SELECT SUM(VALOR) FROM COMPRAS
WHERE DATA > '01-JAN-2010';

SELECT AVG(VALOR) FROM COMPRAS;

SELECT COUNT(ID) FROM COMPRAS
WHERE DATA BETWEEN '01-JAN-2010' AND '31-DEC-2010';

SELECT SUM(VALOR), AVG(VALOR) FROM COMPRAS;

SELECT SUM(VALOR) AS SOMA, AVG(VALOR) AS MEDIA FROM COMPRAS;

SELECT SUM(VALOR) FROM COMPRAS
WHERE RECEBIDO = '1';

SELECT SUM(VALOR) FROM COMPRAS
WHERE RECEBIDO = '0';

SELECT SUM(VALOR) FROM COMPRAS GROUP BY RECEBIDO;

SELECT RECEBIDO, SUM(VALOR) FROM COMPRAS GROUP BY RECEBIDO;

SELECT EXTRACT(YEAR FROM DATA), SUM(VALOR) FROM COMPRAS GROUP BY EXTRACT(YEAR FROM DATA);

SELECT EXTRACT(YEAR FROM DATA) AS ANO, SUM(VALOR) AS SOMA FROM COMPRAS
GROUP BY EXTRACT(YEAR FROM DATA)
ORDER BY ANO;