USE SUCOS_VENDAS

BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\Users\gabrielbertocco\Documents\TESTE\SUCOS_VENDAS.BAK'

BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\Users\gabrielbertocco\Documents\TESTE\SUCOS_VENDAS.BAK' WITH INIT

BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\Users\gabrielbertocco\Documents\TESTE\SUCOS_VENDAS2.BAK' WITH COMPRESSION