USE SUCOS_VENDAS
BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\Users\gabrielbertocco\Documents\TESTE\SUCOS_VENDAS.BAK' WITH INIT

USE master
ALTER DATABASE SUCOS_VENDAS SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE SUCOS_VENDAS RESTORE DATABASE SUCOS_VENDAS FROM DISK = 'C:\Users\gabrielbertocco\Documents\TESTE\SUCOS_VENDAS.BAK' WITH RECOVERY

BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\Users\gabrielbertocco\Documents\TESTE\SUCOS_VENDAS.BAK' WITH INIT
BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\Users\gabrielbertocco\Documents\TESTE\SUCOS_VENDAS.BAK'
BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\Users\gabrielbertocco\Documents\TESTE\SUCOS_VENDAS.BAK'
BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\Users\gabrielbertocco\Documents\TESTE\SUCOS_VENDAS.BAK'

RESTORE HEADERONLY FROM DISK = 'C:\Users\gabrielbertocco\Documents\TESTE\SUCOS_VENDAS.BAK'

RESTORE DATABASE SUCOS_VENDAS FROM DISK = 'C:\Users\gabrielbertocco\Documents\TESTE\SUCOS_VENDAS.BAK'
WITH FILE = 4, RECOVERY