

SELECT RAND()

--- VALOR MINIMO SEJA 100
--- VALOR M�XIMO SEJA 500

SELECT ROUND(((500 - 100 - 1) * RAND() + 100), 0)

-- NÃO VAI RODAR, POIS O RAND() NÃO PODE ESTAR DENTRO DE UM OUTRO MÉTODO
CREATE FUNCTION NumeroAleatorio(@VAL_INIC INT, @VAL_FINAL INT) RETURNS INT
AS
BEGIN
DECLARE @ALEATORIO INT
SET @ALEATORIO = ROUND(((@VAL_FINAL - @VAL_INIC - 1) * RAND() + @VAL_INIC), 0)
RETURN @ALEATORIO
END

-- CRIA UMA VIEW PARA O RAND()
CREATE VIEW VW_ALEATORIO AS SELECT RAND() AS VALUE

SELECT * FROM VW_ALEATORIO

-- AGORA É POSSíVEL ADICIONAR O RAND() NO MÉTODO, COMO UMA VIEW
CREATE FUNCTION NumeroAleatorio(@VAL_INIC INT, @VAL_FINAL INT) RETURNS INT
AS
BEGIN
DECLARE @ALEATORIO INT
DECLARE @ALEATORIO_FLOAT FLOAT
SELECT @ALEATORIO_FLOAT = VALUE FROM VW_ALEATORIO
SET @ALEATORIO = ROUND(((@VAL_FINAL - @VAL_INIC - 1) * @ALEATORIO_FLOAT + @VAL_INIC), 0)
RETURN @ALEATORIO
END

SELECT [dbo].[NumeroAleatorio](1,3)



