CREATE PROCEDURE NumNotasSP
@DATA AS DATE,
@NUMNOTAS AS INT OUTPUT
AS
BEGIN
    DECLARE @NUMNOTASLOCAL INT
    SELECT @NUMNOTASLOCAL = COUNT(*) 
        FROM [NOTAS FISCAIS] WHERE [DATA] = @DATA
    SET @NUMNOTAS = @NUMNOTAS + @NUMNOTASLOCAL
END

DECLARE @DATA DATE
DECLARE @NUMNOTAS INT
SET @NUMNOTAS = 0
SET @DATA = '20170101'
EXEC NumNotasSP @DATA = @DATA, @NUMNOTAS = @NUMNOTAS OUTPUT
SET @DATA = '20170102'
EXEC NumNotasSP @DATA = @DATA, @NUMNOTAS = @NUMNOTAS OUTPUT
PRINT @NUMNOTAS