
CREATE TYPE ListaDatas AS TABLE
( DATANOTA DATE NOT NULL )

CREATE PROCEDURE ListaNumeroNotas @ListaDatas 
    AS ListaDatas READONLY AS
SELECT DATA, COUNT(*) AS NUMERO FROM [NOTAS FISCAIS]
    WHERE DATA IN (SELECT DATANOTA FROM @ListaDatas)
GROUP BY DATA

DECLARE @ListaDatas AS ListaDatas
INSERT INTO @ListaDatas (DATANOTA) VALUES ('20180101'), 
    ('20180102'), ('20180103')
EXEC ListaNumeroNotas @ListaDatas=@ListaDatas