DECLARE @NOME VARCHAR(10), @IDADE INT, @DATA_NASCIMENTO DATE, @CUSTO FLOAT

SET @NOME = 'João'
SET @IDADE = 10
SET @DATA_NASCIMENTO = '20070110'
SET @CUSTO = 10.23

PRINT @NOME
PRINT @IDADE
PRINT @DATA_NASCIMENTO
PRINT @CUSTO