USE [VENDAS_SUCOS]
GO

/****** Object:  Table [dbo].[NOTAS]    Script Date: 16/10/2019 13:10:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ITENS VENDIDOS](
    [NÚMERO] VARCHAR(5) NOT NULL,
    [CÓDIGO] VARCHAR(10) NOT NULL,
    [QUANTIDADE] INT NULL,
    [PREÇO] FLOAT NULL, 
CONSTRAINT [PK_ITENS_VENDIDOS] PRIMARY KEY CLUSTERED (
    [NÚMERO] ASC, [CÓDIGO] ASC
) WITH (
    PAD_INDEX = OFF, 
    STATISTICS_NORECOMPUTE = OFF, 
    IGNORE_DUP_KEY = OFF, 
    ALLOW_ROW_LOCKS = ON, 
    ALLOW_PAGE_LOCKS = ON
) ON [PRIMARY]) ON [PRIMARY]
GO


