UPDATE [CLIENTES] SET 
ENDEREÇO = 'R. Jorge Emilio 23', 
BAIRRO = 'Santo Amaro', 
CIDADE = 'São Paulo', 
ESTADO = 'SP',
CEP = '8833223'
WHERE CPF = '19290992743'

UPDATE CLIENTES SET
[VOLUME COMPRA] = [VOLUME COMPRA] * 1.20
WHERE ESTADO = 'RJ'