INSERT INTO [dbo].[TABELA_DE_PRODUTOS]
(CODIGO_PRODUTO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA)
VALUES
('1040107', 'LIGHT - 350ML - MELÂNCIA', 'LATA', '350ML', 'MELANCIA', 4.56)

INSERT INTO [dbo].[TABELA_DE_PRODUTOS]
(CODIGO_PRODUTO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA)
VALUES
('1037797', 'CLEAN - 2 LITROS - LARANJA', 'PET', '2 LITROS', 'LARANJA', 16.01)

INSERT INTO [dbo].[TABELA_DE_PRODUTOS]
(CODIGO_PRODUTO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA)
VALUES
('1000889', 'SABOR DA MONTANHA - 700ML - UVA', 'GARRAFA', '700ML', 'UVA', 6.31)

INSERT INTO [dbo].[TABELA_DE_PRODUTOS]
(CODIGO_PRODUTO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA)
VALUES
('1004327', 'VIDEIRA DO CAMPO - 1,5 LITROS - MELÂNCIA', 'PET', '1,5 LITROS', 'MELÂNCIA', 19.51)

INSERT INTO [dbo].[TABELA_DE_PRODUTOS]
(CODIGO_PRODUTO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA)
VALUES
('1088126', 'LINHA CITROS - 1 LITRO - LIMÃO', 'PET', '1 LITRO', 'LIMÃO', 7.00)