DROP TABLE TABELA_DE_VENDEDORES

CREATE TABLE TABELA_DE_VENDEDORES
(
MATRICULA VARCHAR(5) ,
NOME VARCHAR(100) ,
PERCENTUAL_COMISSAO FLOAT ,
DATA_ADMISSAO DATE,
DE_FERIAS BIT
)

ALTER TABLE [TABELA_DE_VENDEDORES]
ALTER COLUMN [MATRICULA]
VARCHAR(5) NOT NULL

ALTER TABLE [TABELA_DE_VENDEDORES]
ADD CONSTRAINT PK_VENDEDORES
PRIMARY KEY CLUSTERED ([MATRICULA])

INSERT INTO [TABELA_DE_VENDEDORES]
([MATRICULA], [NOME], [DATA_ADMISSAO], [PERCENTUAL_COMISSAO], [DE_FERIAS])
VALUES
('00235','MÁRCIO ALMEIDA SILVA','2014-08-15',0.08,0)

INSERT INTO TABELA_DE_VENDEDORES
([MATRICULA], [NOME], [DATA_ADMISSAO], [PERCENTUAL_COMISSAO], [DE_FERIAS])
VALUES
('00236', 'CLÁUDIA MORAIS', '2013-09-17', 0.08, 1)

INSERT INTO TABELA_DE_VENDEDORES
([MATRICULA], [NOME], [DATA_ADMISSAO], [PERCENTUAL_COMISSAO], [DE_FERIAS])
VALUES
('00237', 'ROBERTA MARTINS', '2017-03-18', 0.11, 1)

INSERT INTO TABELA_DE_VENDEDORES
([MATRICULA], [NOME], [DATA_ADMISSAO], [PERCENTUAL_COMISSAO], [DE_FERIAS])
VALUES
('00238', 'PERICLES ALVES', '2016-08-21', 0.11, 0)
