UPDATE TABELA_DE_VENDEDORES SET
MATRICULA = '00238' ,
PERCENTUAL_COMISSAO = 0.11
WHERE NOME = 'PERICLES ALVES'

UPDATE TABELA_DE_VENDEDORES SET
MATRICULA = '00233' ,
NOME = 'JOSÉ GERALDO DA FONSECA JUNIOR'
WHERE NOME = 'JOSÉ GERALDO DA FONSECA'
