SELECT A.NOME FROM ALUNO A;

SELECT COUNT(A.ID) FROM ALUNO A;

-- QUERY SELECIONAR APENAS OS CINCO PRIMEIROS ELEMENTOS DE UMA TABELA, ORDENADOS PELO NOME, POR EXEMPLO
SELECT A.NOME FROM ALUNO A
ORDER BY A.NOME;

SELECT ROWNUM FROM (SELECT A.NOME FROM ALUNO A ORDER BY A.NOME);

SET PAGESIZE 20;

SELECT ROWNUM, NOME FROM (SELECT A.NOME FROM ALUNO A ORDER BY A.NOME);

SELECT ROWNUM, NOME FROM (SELECT A.NOME FROM ALUNO A ORDER BY A.NOME)
WHERE ROWNUM <= 5;

-- NÃO VAI DAR CERTO, POIS O ROWNUM COMEÇA SEU INDEX APENAS DEPOIS DO SELECT, OU SEJA, ELE SEMPRE ELIMINARÁ O PRIMEIRO INDEX E, 
-- O PRÓXIMO, SERÁ O INDEX 1, O QUE SERÁ ELIMIDADO, ASSIM SUCESSIVAMENTE.
SELECT ROWNUM, NOME FROM (SELECT A.NOME FROM ALUNO A ORDER BY A.NOME)
WHERE ROWNUM > 5; 

-- PARA DAR CERTO, DEVE-SE COLOCAR O SELECT NUMA SUB-QUERY E DAR UM ALIAS PARA O ROWNUM DA SELEÇÃO INTERNA, PARA QUE ELE POSSA SER
-- O PARÂMETRO DE SELEÇÃO DA QUERY EXTERNA
SELECT * FROM (SELECT ROWNUM AS R, NOME FROM (SELECT A.NOME FROM ALUNO A ORDER BY A.NOME))
WHERE R > 5;

-- EXIBIR OS ALUNOS DO 5 AO 10
SELECT * FROM (SELECT ROWNUM AS R, NOME FROM (SELECT A.NOME FROM ALUNO A ORDER BY A.NOME) WHERE ROWNUM <= 10)
WHERE R > 5;

-- Escreva uma query que ordene os alunos por nome e traga apenas os dois primeiros.
SELECT ROWNUM, NOME FROM
	(SELECT A.NOME FROM ALUNO A ORDER BY A.NOME)
WHERE ROWNUM <= 2;

-- Escreva uma SQL que devolva os 3 primeiros alunos que o e-mail termine com o domínio ".com".
SELECT ROWNUM, NOME, EMAIL FROM
	(SELECT A.NOME, A.EMAIL FROM ALUNO A)
WHERE ROWNUM <= 3 AND EMAIL LIKE ('%.com');

-- Escreva uma query que ordene os alunos por nome, e traga apenas os dois primeiros cujo e-mail termine com ".com".
SELECT ROWNUM, NOME, EMAIL FROM
	(SELECT A.NOME, A.EMAIL FROM ALUNO A ORDER BY A.NOME)
WHERE ROWNUM <= 2 AND EMAIL LIKE ('%.com');