SELECT A.NOME, C.NOME, AVG(N.NOTA) FROM NOTA N
	JOIN RESPOSTA R ON R.ID = N.RESPOSTA_ID
	JOIN EXERCICIO E ON E.ID = R.EXERCICIO_ID
	JOIN SECAO S ON S.ID = E.SECAO_ID
	JOIN CURSO C ON C.ID = S.CURSO_ID
	JOIN ALUNO A ON A.ID = R.ALUNO_ID
GROUP BY C.NOME, A.NOME;

SET LINESIZE 200;

SELECT AVG(N.NOTA) FROM NOTA N;

-- QUERY COM O NOME DO ALUNO, NOME DO CURSO, MÉDIA DO ALUNO NO CURSO E DIFERENÇA PARA A MÉDIA GERAL
SELECT A.NOME, C.NOME, AVG(N.NOTA) AS MEDIA, AVG(N.NOTA) - (SELECT AVG(N.NOTA) FROM NOTA N) AS DIFERENCA FROM NOTA N
	JOIN RESPOSTA R ON R.ID = N.RESPOSTA_ID
	JOIN EXERCICIO E ON E.ID = R.EXERCICIO_ID
	JOIN SECAO S ON S.ID = E.SECAO_ID
	JOIN CURSO C ON C.ID = S.CURSO_ID
	JOIN ALUNO A ON A.ID = R.ALUNO_ID
GROUP BY C.NOME, A.NOME;

-- QUANTAS RESPOSTAS OS ALUNOS DERAM INDIVIDUALMENTE
SELECT A.NOME FROM ALUNO A;

SELECT COUNT(R.ID) FROM RESPOSTA R;

-- SUB-QUERY
SELECT A.NOME, (SELECT COUNT(R.ID) FROM RESPOSTA R WHERE A.ID = R.ALUNO_ID) AS RESPOSTAS FROM ALUNO A;

-- SABER QUANTOS CURSOS UM ALUNO FEZ OU FAZ, OU SEJA, QUANTAS MATRÍCULAS DIFERENTES UM ALUNO TEM
SELECT A.NOME FROM ALUNO A;

SELECT COUNT(M.ID) FROM MATRICULA M;

SELECT A.NOME, (SELECT COUNT(M.ID) FROM MATRICULA M WHERE M.ALUNO_ID = A.ID) AS MATRICULAS FROM ALUNO A;

-- Exiba a média das notas por aluno por curso, além de uma coluna com a diferença entre a média do aluno e a média geral. 
-- Use sub-queries para isso.
SELECT A.NOME               , 
	   C.NOME               , 
	   AVG(N.NOTA) AS MEDIA , 
	   AVG(N.NOTA) - (SELECT AVG(N.NOTA) FROM NOTA N) AS DIFERENCA 
FROM NOTA N
	JOIN RESPOSTA  R ON R.ID = N.RESPOSTA_ID
	JOIN EXERCICIO E ON E.ID = R.EXERCICIO_ID
	JOIN SECAO     S ON S.ID = E.SECAO_ID
	JOIN CURSO     C ON C.ID = S.CURSO_ID
	JOIN ALUNO     A ON A.ID = R.ALUNO_ID
GROUP BY C.NOME, A.NOME;

-- Devolva a média de notas no curso por aluno e a diferença para a média geral.
-- No entanto, exiba apenas alunos que tiveram alguma matrícula nos últimos 6 meses.
SELECT A.NOME ,
	   C.NOME ,
	   AVG(N.NOTA) AS MEDIA ,
	   AVG(N.NOTA) - (SELECT AVG(N.NOTA) FROM NOTA N) AS DIFERENCA
FROM NOTA N
	JOIN RESPOSTA R ON R.ID = N.RESPOSTA_ID
	JOIN EXERCICIO E ON E.ID = R.EXERCICIO_ID
	JOIN SECAO S ON S.ID = E.SECAO_ID
	JOIN CURSO C ON C.ID = S.CURSO_ID
	JOIN ALUNO A ON A.ID = R.ALUNO_ID
WHERE A.ID IN (SELECT ALUNO_ID FROM MATRICULA WHERE DATA > (SELECT SYSDATE - INTERVAL '6' MONTH FROM DUAL))
GROUP BY C.NOME, A.NOME;

-- Qual é o problema de se usar sub-queries?
---- Se a sub-query for mal escrita, ela pode ser executada muitas vezes; geralmente uma para cada linha de resposta da "consulta 
---- de fora". Isso pode fazer com que a consulta leve muito tempo para ser executada, podendo causar lentidão do banco de dados e 
---- das aplicações que o acessam.