SELECT A.NOME, C.NOME, AVG(N.NOTA) FROM ALUNO A
	JOIN RESPOSTA R ON R.ID = N.RESPOSTA_ID
	JOIN EXERCICIO E ON E.ID = R.EXERCICIO_ID
	JOIN SECAO S ON S.ID = E.SECAO_ID
	JOIN CURSO C ON C.ID = S.CURSO_ID
	JOIN ALUNO A ON A.ID = C.ALUNO_ID
WHERE AVG(N.NOTA) < 5
GROUP BY A.NOME, C.NOME;

SELECT A.NOME, C.NOME, AVG(N.NOTA) FROM ALUNO A
	JOIN RESPOSTA R ON R.ID = N.RESPOSTA_ID
	JOIN EXERCICIO E ON E.ID = R.EXERCICIO_ID
	JOIN SECAO S ON S.ID = E.SECAO_ID
	JOIN CURSO C ON C.ID = S.CURSO_ID
	JOIN ALUNO A ON A.ID = C.ALUNO_ID
GROUP BY A.NOME, C.NOME
HAVING AVG(N.NOTA) < 5;

SELECT COUNT(A.ID), C.NOME FROM CURSO C
	JOIN MATRICULA M ON M.CURSO_ID = C.ID
	JOIN ALUNO A ON A.ID = M.ALUNO_ID
GROUP BY C.NOME
HAVING COUNT(A.ID) < 3;

-- Devolva todos os alunos, cursos e a média de suas notas. Lembre-se de agrupar por aluno e por curso. 
-- Filtre também pela nota: só mostre alunos com nota média menor do que 5.
SELECT A.NOME, C.NOME, AVG(N.NOTA) AS MEDIA FROM NOTA N
	JOIN RESPOSTA R ON R.ID = N.RESPOSTA_ID
	JOIN EXERCICIO E ON E.ID = R.EXERCICIO_ID
	JOIN SECAO S ON S.ID = E.SECAO_ID
	JOIN CURSO C ON C.ID = S.CURSO_ID
	JOIN ALUNO A ON A.ID = C.ALUNO_ID
GROUP BY A.NOME, C.NOME
HAVING AVG(N.NOTA) < 5;

-- Exiba todos os cursos e a sua quantidade de matrículas. Mas exiba somente cursos que tenham mais de 1 matrícula.
SELECT C.NOME, COUNT(M.ID) AS QUANTIDADE FROM CURSO C
	JOIN MATRICULA M ON M.CURSO_ID = C.ID
GROUP BY C.NOME
HAVING COUNT(M.ID) > 1;

-- Exiba o nome do curso e a quantidade de seções que existe nele. Mostre só cursos com mais de 3 seções.
SELECT C.NOME, COUNT(S.ID) AS QUANTIDADE FROM CURSO C
	JOIN SECAO S ON C.ID = S.CURSO_ID
GROUP BY C.NOME
HAVING COUNT(S.ID) > 3;